name: MyFirstCICD
run-name: ${{ github.event_name}} by ${{ github.actor }}
on:
  push:
    branches: 
        - main
  pull_request:
    branches:
      - main
jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
      - run: docker compose config -q



    
